<?
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["upload"]["11"]="T_8";
$PERM["/"]["*"]="R";
$PERM["fortest"]["*"]="D";
$PERM["fortest"]["8"]="X";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
?>